tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/homebrew-php"
tap "mapbox/cli"
tap "pothosware/pothos"

# is required for java-based brews, like ant
cask "java"

brew "awscli"
brew "bash"
brew "bash-completion"
brew "colordiff"
brew "coreutils"
brew "ffmpeg"
brew "findutils", args: ["with-default-names"]
brew "git", args: ["with-curl", "with-openssl"]
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar", args: ["with-default-names"]
brew "gnu-time", args: ["with-default-names"]
brew "gnu-which", args: ["with-default-names"]
brew "gnupg"
brew "go"
brew "graphviz"
brew "highlight"
brew "htop"
brew "jo"
brew "jq"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "libxml2"
brew "mas"
brew "mc"
brew "mpv", args: ["with-bundle", "with-libbluray", "with-libcaca", "with-libdvdnav", "with-libdvdread"]
brew "mtr"
brew "packer"
brew "php72", args: ["with-gmp", "with-pear", "with-phpdbg", "without-fpm"]
brew "pinentry-mac"
brew "ruby"
brew "shellcheck"
brew "siege"
brew "sift"
brew "terraform"
brew "tmux"
brew "transcrypt"
brew "unixodbc"
brew "watch"
brew "wget"
brew "wrk"
brew "youtube-dl"

cask "alfred"
cask "bitbar"
cask "caskroom/versions/docker-edge"
cask "caskroom/versions/microsoft-remote-desktop-beta"
cask "ccmenu"
cask "dropbox"
cask "emin-webpquicklook"
cask "enpass"
cask "evernote"
cask "franz"
cask "google-chrome"
cask "hex-fiend"
cask "insomnia"
cask "iterm2"
cask "keepassx"
cask "keybase"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlrest"
cask "qlstephen"
cask "qlvideo"
cask "quickgeojson"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklook-pfm"
cask "sequel-pro"
cask "slack"
cask "sourcetree"
cask "spectacle"
cask "spotifree"
cask "spotify"
cask "tunnelblick"
cask "visual-studio-code"

mas "DrCleaner", id: 921458519
