tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/homebrew-php"
tap "mapbox/cli"
tap "pothosware/pothos"
cask "java"
brew "ant"
brew "awscli"
brew "bash-completion"
brew "colordiff"
brew "composer"
brew "coreutils"
brew "git", args: ["with-curl", "with-openssl"]
brew "ffmpeg"
brew "findutils", args: ["with-default-names"]
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar", args: ["with-default-names"]
brew "gnu-time", args: ["with-default-names"]
brew "gnu-which", args: ["with-default-names"]
brew "gnupg"
brew "go"
brew "graphviz"
brew "highlight"
brew "htop"
brew "jo"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "youtube-dl"
brew "mpv", args: ["with-bundle", "with-libbluray", "with-libcaca", "with-libdvdnav", "with-libdvdread"]
brew "mtr"
brew "pinentry-mac"
brew "php70", args: ["with-gmp", "with-pear", "with-phpdbg", "without-fpm"]
brew "php70-intl"
brew "shellcheck"
brew "siege"
brew "sift"
brew "transcrypt"
brew "tmux"
brew "watch"
brew "wget"
brew "wrk"
cask "alfred"
cask "betterzipql"
cask "bitbar"
cask "calibre"
cask "ccmenu"
cask "coconutbattery"
cask "docker-edge"
cask "dropbox"
cask "easysimbl"
cask "emin-webpquicklook"
cask "evernote"
cask "franz"
cask "gimp"
cask "google-chrome"
cask "hex-fiend"
cask "insomnia"
cask "iterm2"
cask "keepassx"
cask "keybase"
cask "launchrocket"
cask "malwarebytes-anti-malware"
cask "microsoft-remote-desktop-beta"
cask "minikube"
cask "paw"
cask "phpstorm"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlrest"
cask "qlstephen"
cask "qlvideo"
cask "quickgeojson"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklook-pfm"
cask "sequel-pro"
cask "sourcetree"
cask "spectacle"
cask "spotifree"
cask "spotify"
cask "tunnelblick"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "witgui"
mas "DrCleaner", id: 921458519
